# Generated by Django 3.0.4 on 2020-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_verb', models.CharField(max_length=10)),
                ('end_point', models.TextField()),
                ('response_code', models.IntegerField()),
                ('response_time', models.CharField(max_length=7)),
            ],
        ),
    ]
